[licenses]
allow-osi-fsf-free = "either"

[sources.allow-org]
github = ["Distributed-EPFL"]

[advisories]
ignore = [
	# chrono hasn't yet released a fix
	# TODO fix upstream
	"RUSTSEC-2020-0071", "RUSTSEC-2020-0159",
]
