name: deployement

on:
  workflow_run:
    workflows: ["integration"]
    branches: [main]
    types: [completed]

env:
  DEPLOY_USER: at2
  DEPLOY_HOST: srv1.c4dt.org

jobs:
  deploy-ns:
    name: deploy AT2's name service
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        name: cargo build
        with:
          command: build
          args: --bin server --features server

      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1.2.0
        with:
          ssh-host: ${{ env.DEPLOY_HOST }}
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: rsync repository
        run: >
          rsync --archive "$GITHUB_WORKSPACE/target/debug/server"
          "${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }}:at2-ns"

      - name: start service
        run: >
          ssh "${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }}"
            systemctl --user restart at2-ns

  deploy-web:
    name: deploy website
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        name: cargo install trunk wasm-bindgen-cli
        with:
          command: install
          args: trunk wasm-bindgen-cli

      - run: trunk build web/index.html

      - name: FIXME patch thedodd/trunk#196
        run: sed -e s,\"/index-,\"index-,g -e s,\'/index-,\'./index-, -e s,\'/index-,\'index-, -i web/dist/index.html

      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1.2.0
        with:
          ssh-host: ${{ env.DEPLOY_HOST }}
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: rsync repository
        run: >
          rsync --verbose --archive --delete "$GITHUB_WORKSPACE/web/dist/"
          "${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }}:web"
